[package]
name = "mars-core"
version = "1.0.2"
authors = ["Spike Spiegel <spikeonmars@protonmail.com>"]
edition = "2018"
description = "Mars is a fully automated, on-chain credit protocol built on Terra and governed by a decentralised community of users and developers"
license = "GPL-3.0"
repository = "https://github.com/mars-protocol/mars-core"
homepage = "https://marsprotocol.io"
documentation = "https://docs.marsprotocol.io/mars-protocol/developers/protocol-overview"
readme = "README.md"
keywords = ["terra", "cosmwasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
terra-cosmwasm = "2.2.0"

cw2 = { workspace = true }
cw20= { workspace = true }
cw20-base = { worksapce = true, features = ["library"] }

cosmwasm-std = { workspace = true }

schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0.23"

astroport = "1.0"

basset = { git = "https://github.com/lidofinance/lido-terra-contracts", tag = "v1.0.2" }

stader = { git = "https://github.com/sbnair/stader-liquid-token", package = "staking", rev = "cafba59f7fcad69dd68e84c607dd5910921bad57", features = [
  "library",
] }

[profile.release]
overflow-checks = true
